#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 15

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 12

#define SERIAL_NUMBER "nvWgW/lbBLPG"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

